id = "fasm"
name = "FASM"
version = "0.1.0"
schema_version = 1
authors = ["kmschr <kmschr@gmail.com>"]
description = "Syntax highlighting for FASM (flat assembler)"
repository = "https://github.com/kmschr/zed-fasm"

[grammars.fasm]
repository = "https://github.com/Kmschr/tree-sitter-fasm"
rev = "3879d1dca17714026ea8cd8e08a02837960abe82"
